config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  resources :purchase_orders
  resources :chat_rooms, only: [:index, :show] do
    resources :messages, only: [:create]
  end
  devise_for :users

  namespace :api, :defaults => {:format => :json} do
    as :user do
      post   "/sign-in"       => "sessions#create"
      delete "/sign-out"      => "sessions#destroy"
      resources :purchase_orders, only: [:index, :show, :create] do
        member do
          get "status"
        end
      end
    end
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/purchase_order.rb
class PurchaseOrder < ApplicationRecord
  belongs_to :user
  has_one_attached :photo
  validates :description, :reception_date, :shipping_date,
            :status, :address, :category, presence: true
  validates :photo, blob: { content_type: ['image/png', 'image/jpg', 'image/jpeg'], size_range: 1..5.megabytes }
  before_create :set_default_propierties


  STATUS_VALUES = ["Espera", "Enviado", "Entregado", "Rechazado", "Cancelado"]
  CATEGORY_VALUES = ["Telefonía", "Informática", "Electrónica", "Joyería", "Calzado"]


  private

  def set_default_propierties
    self.user = user
    self.status = "Espera"
  end

end

app/controllers/api/purchase_orders_controller.rb
class Api::PurchaseOrdersController < Api::BaseController
  before_action :set_purchase_order, only: [:show, :status]

  # GET /purchase_orders
  # GET /purchase_orders.json
  def index
    @purchase_orders = current_user.purchase_orders
    @purchase_orders = @purchase_orders.map{ |purchase_order| purchase_order.attributes }
    render json: @purchase_orders
  end

  # GET /purchase_orders/1
  # GET /purchase_orders/1.json
  def show
    authorize @purchase_order
    render json: @purchase_order.attributes
  end

  def status
    authorize @purchase_order
    render json: {purchase_order: @purchase_order.slice(:id, :status)}
  end

  # POST /purchase_orders
  # POST /purchase_orders.json
  def create
    @purchase_order = PurchaseOrder.new(purchase_order_params)
    @purchase_order.user = current_user
    @purchase_order.status = "Espera"

    if @purchase_order.save
      render json: {status: "created", purchase_order: @purchase_order.attributes}
      # render :show, status: :created, location: @purchase_order
      # format.html { redirect_to purchase_orders_path, notice: 'Purchase order was successfully created.' }
      # format.json { render :show, status: :created, location: @purchase_order }
    else
      render json: @purchase_order.errors, status: :unprocessable_entity
      # format.html { render :new }
      # format.json { render json: @purchase_order.errors, status: :unprocessable_entity }
    end
  end


  # DELETE /purchase_orders/1

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_purchase_order
      @purchase_order = PurchaseOrder.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def purchase_order_params
      params.require(:purchase_order).permit(:description, :status, :category,
                                             :shipping_date, :reception_date, :address)
    end
end

app/controllers/purchase_orders_controller.rb
class PurchaseOrdersController < ApplicationController
  before_action :set_purchase_order, only: [:show, :edit, :update, :destroy]

  # GET /purchase_orders
  # GET /purchase_orders.json
  def index
    @purchase_orders = policy_scope(PurchaseOrder).all
  end

  # GET /purchase_orders/1
  # GET /purchase_orders/1.json
  def show
    authorize @purchase_order
  end

  # GET /purchase_orders/new
  def new
    @purchase_order = PurchaseOrder.new
  end

  # GET /purchase_orders/1/edit
  def edit
    authorize @purchase_order
  end

  # POST /purchase_orders
  # POST /purchase_orders.json
  def create
    @purchase_order = PurchaseOrder.new(purchase_order_params)
    @purchase_order.user = current_user
    @purchase_order.status = "Espera"

    respond_to do |format|
      if @purchase_order.save
        format.html { redirect_to purchase_orders_path, notice: 'Purchase order was successfully created.' }
        format.json { render :show, status: :created, location: @purchase_order }
      else
        format.html { render :new }
        format.json { render json: @purchase_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /purchase_orders/1
  # PATCH/PUT /purchase_orders/1.json
  def update
    authorize @purchase_order
    respond_to do |format|
      if @purchase_order.update(purchase_order_params)
        format.html { redirect_to purchase_orders_path, notice: 'Purchase order was successfully updated.' }
        format.json { render :show, status: :ok, location: @purchase_order }
      else
        format.html { render :edit }
        format.json { render json: @purchase_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /purchase_orders/1
  # DELETE /purchase_orders/1.json
  def destroy
    authorize @purchase_order
    @purchase_order.destroy
    respond_to do |format|
      format.html { redirect_to purchase_orders_url, notice: 'Purchase order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_purchase_order
      @purchase_order = PurchaseOrder.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def purchase_order_params
      params.require(:purchase_order).permit(:description, :photo, :user_id, :status, :category,
                                             :shipping_date, :reception_date, :address)
    end
end

app/helpers/purchase_orders_helper.rb
module PurchaseOrdersHelper
end

app/views/purchase_orders/_form.html.slim
= simple_form_for(@purchase_order, defaults: {input_html: {class: "form_space"}, label_html: {class: "label_space"} }) do |f|
  = f.error_notification

  .form-inputs
    = f.input :description, label: "Descripción", input_html: {class: "form_description"}
    = f.input :category, collection: PurchaseOrder::CATEGORY_VALUES, label: "Categoría"
    / = f.file_field :photo
    = f.input :photo, label: "Foto"
    - if current_user.admin?
      = f.input :status, collection: PurchaseOrder::STATUS_VALUES, label: "Estado"
    = f.input :address, label: "Dirección de destino"
    = f.input :shipping_date, as: :date, label: "Fecha de envío"
    = f.input :reception_date, as: :date, label: "Fecha de recepción"

  .form-actions
    = f.button :submit, "Guardar", class: "btn btn-success"

app/views/purchase_orders/edit.html.slim
h1.form_title Editar pedido

== render 'form'

app/views/purchase_orders/index.html.slim
h1 Listado de pedidos

table.table.table-striped.table-hover
  thead
    tr
      th Id
      th Descripción
      / th Foto
      - if current_user.admin?
        th Usuario
      th Estado
      th Fecha de creación
      th Fecha de envío
      th Fecha de recepción
      th
      - if current_user.admin?
        th
        th

  tbody
    - @purchase_orders.each do |purchase_order|
      tr
        td = purchase_order.id
        td = purchase_order.description
        / td = purchase_order.photo
        - if current_user.admin?
          td = purchase_order.user
        td = purchase_order.status
        td = purchase_order.created_at.strftime("%d/%m/%Y")
        td = purchase_order.shipping_date.strftime("%d/%m/%Y")
        td = purchase_order.reception_date.strftime("%d/%m/%Y")
        td = link_to 'Mostrar', purchase_order
        - if current_user.admin?
          td = link_to 'Editar', edit_purchase_order_path(purchase_order)
          td = link_to 'Eliminar', purchase_order, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'Nuevo pedido', new_purchase_order_path

app/views/purchase_orders/new.html.slim
h1.form_title Nuevo pedido

== render 'form'

app/views/purchase_orders/show.html.slim
h1 Detalles de pedido

- if current_user.admin?
  p
    strong> User:
    = @purchase_order.user

p
  strong> Id:
  = @purchase_order.id

p
  strong> Descripción:
  = @purchase_order.description

p
  strong> Categoría:
  = @purchase_order.category

p
  strong> Foto:
  - if @purchase_order.photo.present?
    br
    = image_tag(@purchase_order.photo)

p
  strong> Dirección de destino:
  = @purchase_order.address

p
  strong> Estado:
  = @purchase_order.status


p
  strong> Fecha de entrega:
  = @purchase_order.shipping_date.strftime("%d/%m/%Y")
p
  strong> Fecha de recepción:
  = @purchase_order.reception_date.strftime("%d/%m/%Y")