config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  resources :purchase_orders
  resources :chat_rooms, only: [:index, :show] do
    resources :messages, only: [:create]
  end
  devise_for :users

  namespace :api, :defaults => {:format => :json} do
    as :user do
      post   "/sign-in"       => "sessions#create"
      delete "/sign-out"      => "sessions#destroy"
      resources :purchase_orders, only: [:index, :show, :create] do
        member do
          get "status"
        end
      end
    end
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_flashes.html.slim
.row
  - flash.each do |msg_type, message|
    .div class = "alert alert-warning alert-dismissible fade show" role="alert"
      button.close aria-label="Close" data-dismiss="alert" type="button"
        span aria-hidden="true"  &times;
      strong= message

app/views/layouts/_nav_bar.html.slim
nav.navbar.navbar-expand-lg.navbar-dark.bg-primary.justify-content-between
    .container
      a.navbar-brand href="#{root_path}"
        => fa_icon "square"
        span Inicio
      button.navbar-toggler aria-controls="navbarNavDropdown" aria-expanded="false" aria-label=("Toggle navigation") data-target="#navbarNavDropdown" data-toggle="collapse" type="button"
        span.navbar-toggler-icon
      #navbarNavDropdown.collapse.navbar-collapse
        ul.navbar-nav.ml-auto
          - if user_signed_in?
            li.nav-item.dropdown
              a#navbarDropdownMenuLink.nav-link.dropdown-toggle aria-expanded="false" aria-haspopup="true" data-toggle="dropdown" href="#"
                | Pedidos
              .dropdown-menu aria-labelledby="navbarDropdownMenuLink"
                a.dropdown-item href="#{purchase_orders_path}"  Listado
                a.dropdown-item href="#{new_purchase_order_path}"  Nuevo pedido
            li.nav-item
              - if current_user.admin?
                a.nav-link href="#{chat_rooms_path}" Chat
              - else
                a.nav-link href="#{chat_room_path(current_user.chat_rooms.first)}" Chat
            li.nav-item.dropdown
              a#navbarDropdownMenuLink.nav-link.dropdown-toggle aria-expanded="false" aria-haspopup="true" data-toggle="dropdown" href="#"
                = current_user.email
              .dropdown-menu aria-labelledby="navbarDropdownMenuLink"
                / a.dropdown-item href=""  Datos
                = link_to "Cerrar sesión", destroy_user_session_path, :method => :delete, class: "dropdown-item"

          - else
            li.nav-item
              a.nav-link href="#{new_user_session_path}" Iniciar Sesión
            li.nav-item
              a.nav-link href="#{new_user_registration_path}" Registrarse

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type"
    meta name="viewport" content="width=device-width, initial-scale=1"
    title RetoTekton
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    = render "layouts/nav_bar"
    .container
      = render "layouts/flashes"
      br
      = yield